#!/bin/bash --login
# we want all these files to exist in the actual package
required_files=(".VERSION" "LICENSE" "AUTHORS.rst" "CONTRIBUTING.rst" "HISTORY.rst" "README.rst" "USAGE.rst" "Pipfile" "Pipfile.lock" "requirements.txt" "dev-requirements.txt")

cd $(dirname $0)/../..

. _CI/scripts/bootstrap
set -e

# cleaning up directories if exist
rm -rf build dist

echo "Locking requirements to create up to date files"
pipenv lock

echo "Creating requiremens.txt"
./_CI/bin/create_requirements.py default

echo "Creating dev-requiremens.txt"
./_CI/bin/create_requirements.py develop


# copy files in the structure
for file in "${required_files[@]}"
    do
        cp $file slacksound/$file
    done

# package
python setup.py sdist bdist_egg

# remove files from the structure
for file in "${required_files[@]}"
    do
        rm slacksound/$file
    done

echo "Removing requiremens.txt"
rm requirements.txt

echo "Removing dev-requiremens.txt"
rm dev-requirements.txt
