#!/bin/bash --login
cd $(dirname $0)/../..

. ./_CI/scripts/bootstrap

# cleaing up the directory
rm -rf test-output
mkdir -p test-output

echo "Locking requirements to create up to date files"
pipenv lock

echo "Creating requiremens.txt"
./_CI/bin/create_requirements.py default

echo "Creating dev-requiremens.txt"
./_CI/bin/create_requirements.py develop

# we run tox
pipenv run tox

exit_code=$?
open test-output/coverage/index.html 2> /dev/null|| xdg-open test-output/coverage/index.html &
sleep 1
open test-output/nosetests.html 2> /dev/null|| xdg-open test-output/nosetests.html &

# cleaning up from requirements files
rm requirements.txt
rm dev-requirements.txt
exit $exit_code
